# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import patient_pb2 as patient__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in patient_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PatientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPatient = channel.unary_unary(
                '/patient.PatientService/GetPatient',
                request_serializer=patient__pb2.GetPatientRequest.SerializeToString,
                response_deserializer=patient__pb2.PatientResponse.FromString,
                _registered_method=True)
        self.CreatePatient = channel.unary_unary(
                '/patient.PatientService/CreatePatient',
                request_serializer=patient__pb2.CreatePatientRequest.SerializeToString,
                response_deserializer=patient__pb2.PatientResponse.FromString,
                _registered_method=True)
        self.UpdatePatient = channel.unary_unary(
                '/patient.PatientService/UpdatePatient',
                request_serializer=patient__pb2.UpdatePatientRequest.SerializeToString,
                response_deserializer=patient__pb2.PatientResponse.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/patient.PatientService/GetHistory',
                request_serializer=patient__pb2.GetHistoryRequest.SerializeToString,
                response_deserializer=patient__pb2.HistoryListResponse.FromString,
                _registered_method=True)
        self.AddHistory = channel.unary_unary(
                '/patient.PatientService/AddHistory',
                request_serializer=patient__pb2.AddHistoryRequest.SerializeToString,
                response_deserializer=patient__pb2.HistoryResponse.FromString,
                _registered_method=True)
        self.GetMemos = channel.unary_unary(
                '/patient.PatientService/GetMemos',
                request_serializer=patient__pb2.GetMemosRequest.SerializeToString,
                response_deserializer=patient__pb2.MemoListResponse.FromString,
                _registered_method=True)
        self.CreateTextMemo = channel.unary_unary(
                '/patient.PatientService/CreateTextMemo',
                request_serializer=patient__pb2.CreateTextMemoRequest.SerializeToString,
                response_deserializer=patient__pb2.MemoResponse.FromString,
                _registered_method=True)
        self.CreateFileMemo = channel.unary_unary(
                '/patient.PatientService/CreateFileMemo',
                request_serializer=patient__pb2.CreateFileMemoRequest.SerializeToString,
                response_deserializer=patient__pb2.MemoResponse.FromString,
                _registered_method=True)
        self.CreateDoctorRecord = channel.unary_unary(
                '/patient.PatientService/CreateDoctorRecord',
                request_serializer=patient__pb2.CreateDoctorRecordRequest.SerializeToString,
                response_deserializer=patient__pb2.MemoResponse.FromString,
                _registered_method=True)


class PatientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTextMemo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFileMemo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDoctorRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatient,
                    request_deserializer=patient__pb2.GetPatientRequest.FromString,
                    response_serializer=patient__pb2.PatientResponse.SerializeToString,
            ),
            'CreatePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePatient,
                    request_deserializer=patient__pb2.CreatePatientRequest.FromString,
                    response_serializer=patient__pb2.PatientResponse.SerializeToString,
            ),
            'UpdatePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePatient,
                    request_deserializer=patient__pb2.UpdatePatientRequest.FromString,
                    response_serializer=patient__pb2.PatientResponse.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=patient__pb2.GetHistoryRequest.FromString,
                    response_serializer=patient__pb2.HistoryListResponse.SerializeToString,
            ),
            'AddHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.AddHistory,
                    request_deserializer=patient__pb2.AddHistoryRequest.FromString,
                    response_serializer=patient__pb2.HistoryResponse.SerializeToString,
            ),
            'GetMemos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemos,
                    request_deserializer=patient__pb2.GetMemosRequest.FromString,
                    response_serializer=patient__pb2.MemoListResponse.SerializeToString,
            ),
            'CreateTextMemo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTextMemo,
                    request_deserializer=patient__pb2.CreateTextMemoRequest.FromString,
                    response_serializer=patient__pb2.MemoResponse.SerializeToString,
            ),
            'CreateFileMemo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFileMemo,
                    request_deserializer=patient__pb2.CreateFileMemoRequest.FromString,
                    response_serializer=patient__pb2.MemoResponse.SerializeToString,
            ),
            'CreateDoctorRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDoctorRecord,
                    request_deserializer=patient__pb2.CreateDoctorRecordRequest.FromString,
                    response_serializer=patient__pb2.MemoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'patient.PatientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('patient.PatientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientService/GetPatient',
            patient__pb2.GetPatientRequest.SerializeToString,
            patient__pb2.PatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientService/CreatePatient',
            patient__pb2.CreatePatientRequest.SerializeToString,
            patient__pb2.PatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientService/UpdatePatient',
            patient__pb2.UpdatePatientRequest.SerializeToString,
            patient__pb2.PatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientService/GetHistory',
            patient__pb2.GetHistoryRequest.SerializeToString,
            patient__pb2.HistoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientService/AddHistory',
            patient__pb2.AddHistoryRequest.SerializeToString,
            patient__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientService/GetMemos',
            patient__pb2.GetMemosRequest.SerializeToString,
            patient__pb2.MemoListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTextMemo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientService/CreateTextMemo',
            patient__pb2.CreateTextMemoRequest.SerializeToString,
            patient__pb2.MemoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFileMemo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientService/CreateFileMemo',
            patient__pb2.CreateFileMemoRequest.SerializeToString,
            patient__pb2.MemoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDoctorRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientService/CreateDoctorRecord',
            patient__pb2.CreateDoctorRecordRequest.SerializeToString,
            patient__pb2.MemoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
