#!/bin/sh
set -eu

ROOT_DIR=$(cd "$(dirname "$0")/../.." && pwd)
INFRA_DIR="$ROOT_DIR/infra"
KONG_ENV="$INFRA_DIR/env/kong.env"
TMP_PEM="/tmp/scq-jwks.pem"

cd "$INFRA_DIR"

echo "[1/9] Checking Docker daemon..."
if ! docker info >/dev/null 2>&1; then
  echo "Docker daemon is not running. Start Docker Desktop and rerun this script."
  exit 1
fi

echo "[2/9] Starting base services..."
docker compose up -d --build rabbitmq app-db

echo "[3/9] Waiting for app-db and applying schema..."
for _ in $(seq 1 60); do
  if docker compose exec -T app-db pg_isready -U app -d clinic >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

if ! docker compose exec -T app-db pg_isready -U app -d clinic >/dev/null 2>&1; then
  echo "app-db did not become ready in time."
  exit 1
fi

docker compose exec -T app-db \
  psql -U app -d clinic -v ON_ERROR_STOP=1 \
  -f /docker-entrypoint-initdb.d/00-schema.sql >/dev/null

echo "[4/9] Starting auth-service..."
docker compose up -d --build auth-service

echo "[5/9] Waiting for auth-service JWKS endpoint..."
for _ in $(seq 1 60); do
  if curl -sf "http://localhost:3000/api/auth/jwks" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

if ! curl -sf "http://localhost:3000/api/auth/jwks" >/dev/null 2>&1; then
  echo "auth-service JWKS endpoint did not become ready in time."
  exit 1
fi

echo "[6/9] Extracting JWKS RSA public key and updating kong.env..."
sh "$INFRA_DIR/scripts/extract-jwks-pem.sh" "http://localhost:3000" \
  | awk '/-----BEGIN PUBLIC KEY-----/{flag=1} flag{print} /-----END PUBLIC KEY-----/{flag=0}' > "$TMP_PEM"

if [ ! -s "$TMP_PEM" ]; then
  echo "Failed to extract PEM from JWKS output."
  exit 1
fi

{
  echo "# RSA public key from BetterAuth JWKS endpoint."
  echo "# Auto-generated by infra/scripts/bringup-and-verify-local.sh"
  echo "BETTER_AUTH_RSA_PUBLIC_KEY=\"$(cat "$TMP_PEM")\""
} > "$KONG_ENV"

echo "[7/9] Starting full stack and reloading Kong..."
docker compose up -d --build

echo "[8/9] Seeding local demo users..."
cd "$ROOT_DIR"
sh infra/scripts/seed-users.sh

echo "[9/9] Running integration tests..."
sh infra/tests/test-staff-orchestrator.sh

for f in infra/tests/*.sh; do
  if [ "$f" = "infra/tests/test-staff-orchestrator.sh" ]; then
    continue
  fi
  echo ""
  echo "== Running $f =="
  sh "$f"
done

echo ""
echo "Local bring-up and verification completed successfully."
