# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doctor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'doctor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64octor.proto\x12\x06\x64octor\"%\n\x10GetDoctorRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\t\"*\n\x15GetDoctorSlotsRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\t\":\n\x17UpdateSlotStatusRequest\x12\x0f\n\x07slot_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x14\n\x12ListDoctorsRequest\"g\n\x0e\x44octorResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0especialisation\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\":\n\x0f\x44octorsResponse\x12\'\n\x07\x64octors\x18\x01 \x03(\x0b\x32\x16.doctor.DoctorResponse\"c\n\x0cSlotResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdoctor_id\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\":\n\x13\x44octorSlotsResponse\x12#\n\x05slots\x18\x01 \x03(\x0b\x32\x14.doctor.SlotResponse2\xab\x02\n\rDoctorService\x12=\n\tGetDoctor\x12\x18.doctor.GetDoctorRequest\x1a\x16.doctor.DoctorResponse\x12L\n\x0eGetDoctorSlots\x12\x1d.doctor.GetDoctorSlotsRequest\x1a\x1b.doctor.DoctorSlotsResponse\x12I\n\x10UpdateSlotStatus\x12\x1f.doctor.UpdateSlotStatusRequest\x1a\x14.doctor.SlotResponse\x12\x42\n\x0bListDoctors\x12\x1a.doctor.ListDoctorsRequest\x1a\x17.doctor.DoctorsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doctor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDOCTORREQUEST']._serialized_start=24
  _globals['_GETDOCTORREQUEST']._serialized_end=61
  _globals['_GETDOCTORSLOTSREQUEST']._serialized_start=63
  _globals['_GETDOCTORSLOTSREQUEST']._serialized_end=105
  _globals['_UPDATESLOTSTATUSREQUEST']._serialized_start=107
  _globals['_UPDATESLOTSTATUSREQUEST']._serialized_end=165
  _globals['_LISTDOCTORSREQUEST']._serialized_start=167
  _globals['_LISTDOCTORSREQUEST']._serialized_end=187
  _globals['_DOCTORRESPONSE']._serialized_start=189
  _globals['_DOCTORRESPONSE']._serialized_end=292
  _globals['_DOCTORSRESPONSE']._serialized_start=294
  _globals['_DOCTORSRESPONSE']._serialized_end=352
  _globals['_SLOTRESPONSE']._serialized_start=354
  _globals['_SLOTRESPONSE']._serialized_end=453
  _globals['_DOCTORSLOTSRESPONSE']._serialized_start=455
  _globals['_DOCTORSLOTSRESPONSE']._serialized_end=513
  _globals['_DOCTORSERVICE']._serialized_start=516
  _globals['_DOCTORSERVICE']._serialized_end=815
# @@protoc_insertion_point(module_scope)
