# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import doctor_pb2 as doctor__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in doctor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DoctorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDoctor = channel.unary_unary(
                '/doctor.DoctorService/GetDoctor',
                request_serializer=doctor__pb2.GetDoctorRequest.SerializeToString,
                response_deserializer=doctor__pb2.DoctorResponse.FromString,
                _registered_method=True)
        self.GetDoctorSlots = channel.unary_unary(
                '/doctor.DoctorService/GetDoctorSlots',
                request_serializer=doctor__pb2.GetDoctorSlotsRequest.SerializeToString,
                response_deserializer=doctor__pb2.DoctorSlotsResponse.FromString,
                _registered_method=True)
        self.UpdateSlotStatus = channel.unary_unary(
                '/doctor.DoctorService/UpdateSlotStatus',
                request_serializer=doctor__pb2.UpdateSlotStatusRequest.SerializeToString,
                response_deserializer=doctor__pb2.SlotResponse.FromString,
                _registered_method=True)
        self.ListDoctors = channel.unary_unary(
                '/doctor.DoctorService/ListDoctors',
                request_serializer=doctor__pb2.ListDoctorsRequest.SerializeToString,
                response_deserializer=doctor__pb2.DoctorsResponse.FromString,
                _registered_method=True)


class DoctorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDoctor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDoctorSlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSlotStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDoctors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DoctorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDoctor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDoctor,
                    request_deserializer=doctor__pb2.GetDoctorRequest.FromString,
                    response_serializer=doctor__pb2.DoctorResponse.SerializeToString,
            ),
            'GetDoctorSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDoctorSlots,
                    request_deserializer=doctor__pb2.GetDoctorSlotsRequest.FromString,
                    response_serializer=doctor__pb2.DoctorSlotsResponse.SerializeToString,
            ),
            'UpdateSlotStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSlotStatus,
                    request_deserializer=doctor__pb2.UpdateSlotStatusRequest.FromString,
                    response_serializer=doctor__pb2.SlotResponse.SerializeToString,
            ),
            'ListDoctors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDoctors,
                    request_deserializer=doctor__pb2.ListDoctorsRequest.FromString,
                    response_serializer=doctor__pb2.DoctorsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doctor.DoctorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('doctor.DoctorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DoctorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDoctor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doctor.DoctorService/GetDoctor',
            doctor__pb2.GetDoctorRequest.SerializeToString,
            doctor__pb2.DoctorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDoctorSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doctor.DoctorService/GetDoctorSlots',
            doctor__pb2.GetDoctorSlotsRequest.SerializeToString,
            doctor__pb2.DoctorSlotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSlotStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doctor.DoctorService/UpdateSlotStatus',
            doctor__pb2.UpdateSlotStatusRequest.SerializeToString,
            doctor__pb2.SlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDoctors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doctor.DoctorService/ListDoctors',
            doctor__pb2.ListDoctorsRequest.SerializeToString,
            doctor__pb2.DoctorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
