# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import queue_pb2 as queue__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in queue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQueuePosition = channel.unary_unary(
                '/queue.QueueService/GetQueuePosition',
                request_serializer=queue__pb2.AppointmentRequest.SerializeToString,
                response_deserializer=queue__pb2.QueuePositionResponse.FromString,
                _registered_method=True)
        self.CheckIn = channel.unary_unary(
                '/queue.QueueService/CheckIn',
                request_serializer=queue__pb2.CallerRequest.SerializeToString,
                response_deserializer=queue__pb2.QueueEntryResponse.FromString,
                _registered_method=True)
        self.AddToQueue = channel.unary_unary(
                '/queue.QueueService/AddToQueue',
                request_serializer=queue__pb2.AddToQueueRequest.SerializeToString,
                response_deserializer=queue__pb2.QueueEntryResponse.FromString,
                _registered_method=True)
        self.RemoveFromQueue = channel.unary_unary(
                '/queue.QueueService/RemoveFromQueue',
                request_serializer=queue__pb2.AppointmentRequest.SerializeToString,
                response_deserializer=queue__pb2.QueueEntryResponse.FromString,
                _registered_method=True)
        self.MarkNoShow = channel.unary_unary(
                '/queue.QueueService/MarkNoShow',
                request_serializer=queue__pb2.AppointmentRequest.SerializeToString,
                response_deserializer=queue__pb2.QueueEntryResponse.FromString,
                _registered_method=True)
        self.CompleteAppointment = channel.unary_unary(
                '/queue.QueueService/CompleteAppointment',
                request_serializer=queue__pb2.AppointmentRequest.SerializeToString,
                response_deserializer=queue__pb2.QueueEntryResponse.FromString,
                _registered_method=True)
        self.CallNext = channel.unary_unary(
                '/queue.QueueService/CallNext',
                request_serializer=queue__pb2.CallNextRequest.SerializeToString,
                response_deserializer=queue__pb2.QueueEntryResponse.FromString,
                _registered_method=True)


class QueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetQueuePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkNoShow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQueuePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueuePosition,
                    request_deserializer=queue__pb2.AppointmentRequest.FromString,
                    response_serializer=queue__pb2.QueuePositionResponse.SerializeToString,
            ),
            'CheckIn': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckIn,
                    request_deserializer=queue__pb2.CallerRequest.FromString,
                    response_serializer=queue__pb2.QueueEntryResponse.SerializeToString,
            ),
            'AddToQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToQueue,
                    request_deserializer=queue__pb2.AddToQueueRequest.FromString,
                    response_serializer=queue__pb2.QueueEntryResponse.SerializeToString,
            ),
            'RemoveFromQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromQueue,
                    request_deserializer=queue__pb2.AppointmentRequest.FromString,
                    response_serializer=queue__pb2.QueueEntryResponse.SerializeToString,
            ),
            'MarkNoShow': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkNoShow,
                    request_deserializer=queue__pb2.AppointmentRequest.FromString,
                    response_serializer=queue__pb2.QueueEntryResponse.SerializeToString,
            ),
            'CompleteAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteAppointment,
                    request_deserializer=queue__pb2.AppointmentRequest.FromString,
                    response_serializer=queue__pb2.QueueEntryResponse.SerializeToString,
            ),
            'CallNext': grpc.unary_unary_rpc_method_handler(
                    servicer.CallNext,
                    request_deserializer=queue__pb2.CallNextRequest.FromString,
                    response_serializer=queue__pb2.QueueEntryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'queue.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('queue.QueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetQueuePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/GetQueuePosition',
            queue__pb2.AppointmentRequest.SerializeToString,
            queue__pb2.QueuePositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/CheckIn',
            queue__pb2.CallerRequest.SerializeToString,
            queue__pb2.QueueEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/AddToQueue',
            queue__pb2.AddToQueueRequest.SerializeToString,
            queue__pb2.QueueEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/RemoveFromQueue',
            queue__pb2.AppointmentRequest.SerializeToString,
            queue__pb2.QueueEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkNoShow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/MarkNoShow',
            queue__pb2.AppointmentRequest.SerializeToString,
            queue__pb2.QueueEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/CompleteAppointment',
            queue__pb2.AppointmentRequest.SerializeToString,
            queue__pb2.QueueEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queue.QueueService/CallNext',
            queue__pb2.CallNextRequest.SerializeToString,
            queue__pb2.QueueEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
