# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: queue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqueue.proto\x12\x05queue\",\n\x12\x41ppointmentRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\":\n\rCallerRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\x12\x11\n\tcaller_id\x18\x02 \x01(\t\"w\n\x11\x41\x64\x64ToQueueRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\x12\x12\n\npatient_id\x18\x02 \x01(\t\x12\x11\n\tdoctor_id\x18\x03 \x01(\t\x12\x0f\n\x07session\x18\x04 \x01(\t\x12\x12\n\nstart_time\x18\x05 \x01(\t\"5\n\x0f\x43\x61llNextRequest\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\x11\n\tdoctor_id\x18\x02 \x01(\t\"U\n\x15QueuePositionResponse\x12\x14\n\x0cqueue_number\x18\x01 \x01(\x05\x12\x16\n\x0e\x65stimated_time\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"\xa2\x01\n\x12QueueEntryResponse\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\x12\x12\n\npatient_id\x18\x02 \x01(\t\x12\x11\n\tdoctor_id\x18\x03 \x01(\t\x12\x0f\n\x07session\x18\x04 \x01(\t\x12\x14\n\x0cqueue_number\x18\x05 \x01(\x05\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x16\n\x0e\x65stimated_time\x18\x07 \x01(\t2\xf3\x03\n\x0cQueueService\x12K\n\x10GetQueuePosition\x12\x19.queue.AppointmentRequest\x1a\x1c.queue.QueuePositionResponse\x12:\n\x07\x43heckIn\x12\x14.queue.CallerRequest\x1a\x19.queue.QueueEntryResponse\x12\x41\n\nAddToQueue\x12\x18.queue.AddToQueueRequest\x1a\x19.queue.QueueEntryResponse\x12G\n\x0fRemoveFromQueue\x12\x19.queue.AppointmentRequest\x1a\x19.queue.QueueEntryResponse\x12\x42\n\nMarkNoShow\x12\x19.queue.AppointmentRequest\x1a\x19.queue.QueueEntryResponse\x12K\n\x13\x43ompleteAppointment\x12\x19.queue.AppointmentRequest\x1a\x19.queue.QueueEntryResponse\x12=\n\x08\x43\x61llNext\x12\x16.queue.CallNextRequest\x1a\x19.queue.QueueEntryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPOINTMENTREQUEST']._serialized_start=22
  _globals['_APPOINTMENTREQUEST']._serialized_end=66
  _globals['_CALLERREQUEST']._serialized_start=68
  _globals['_CALLERREQUEST']._serialized_end=126
  _globals['_ADDTOQUEUEREQUEST']._serialized_start=128
  _globals['_ADDTOQUEUEREQUEST']._serialized_end=247
  _globals['_CALLNEXTREQUEST']._serialized_start=249
  _globals['_CALLNEXTREQUEST']._serialized_end=302
  _globals['_QUEUEPOSITIONRESPONSE']._serialized_start=304
  _globals['_QUEUEPOSITIONRESPONSE']._serialized_end=389
  _globals['_QUEUEENTRYRESPONSE']._serialized_start=392
  _globals['_QUEUEENTRYRESPONSE']._serialized_end=554
  _globals['_QUEUESERVICE']._serialized_start=557
  _globals['_QUEUESERVICE']._serialized_end=1056
# @@protoc_insertion_point(module_scope)
